### ISSUE TITLE
Cryptic NCCL errors

### ISSUE THREAD

**Issue by oxysoft** [willccbb/verifiers#78]
This is my server command

```
MPLBACKEND="agg"  CUDA_VISIBLE_DEVICES=0,1  NCCL_DEBUG=INFO  vf-vllm --model 'Qwen/Qwen2.5-1.5B-Instruct' --tensor-parallel-size 2 --gpu-memory-utilization 0.5
```

My GRPOTrainer connects and this is the result:

```
INFO 06-07 17:34:08 [importing.py:53] Triton module has been replaced with a placeholder.
INFO 06-07 17:34:09 [__init__.py:239] Automatically detected platform cuda.
─────────────────────── 🧠 Symbolic Compressor Training ────────────────────────
Base model: Qwen/Qwen2.5-1.5B-Instruct
Stages: identity → structured → freeform → cognition
────────────────────────────────────────────────────────────────────────────────

───────────────────────────── Stage 1/4: IDENTITY ──────────────────────────────
Identity Pretraining: Learn basic compress → decompress → match
α=0.005 β=3.0
────────────────────────────────────────────────────────────────────────────────

📊 Loading dataset...
✓ Wikipedia dataset loaded
✓ Split: 1450 train, 50 eval

🏗️ Setting up environment...
✓ Environment ready

🚀 Training...
📦 Loading model: Qwen/Qwen2.5-1.5B-Instruct
Using Liger kernel
Applied Liger kernels to Qwen2
✓ Model loaded

⚙️ Configuring training...
                                                      
  Alpha (compression)         0.005                   
  Beta (fidelity)             3.0                     
  Max steps                   150                     
  Training samples            1450                    
  Batch size                  2 prompts → 4 rollouts  
                                                      

🏋️ Creating trainer...
[2025-06-07 17:34:15,257] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2025-06-07 17:34:16 - verifiers.trainers.grpo_trainer - INFO - Filtering dataset for prompts with length <= 1024
2025-06-07 17:34:17 - verifiers.inference.vllm_client - INFO - Server is not up yet. Retrying in 2.0 seconds...
2025-06-07 17:34:19 - verifiers.inference.vllm_client - INFO - Server is not up yet. Retrying in 2.0 seconds...
2025-06-07 17:34:21 - verifiers.inference.vllm_client - INFO - Server is not up yet. Retrying in 2.0 seconds...
2025-06-07 17:34:23 - verifiers.inference.vllm_client - INFO - Server is not up yet. Retrying in 2.0 seconds...
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - Server is up!
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] Starting init_communicator
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] Getting world size from http://0.0.0.0:8000/get_world_size/
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] World size response: status=200
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] vLLM world size: 2
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] Client rank: 2, total world size: 3
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] Sending init_communicator request to http://0.0.0.0:8000/init_communicator/
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] Init communicator response: status=200
2025-06-07 17:34:25 - verifiers.inference.vllm_client - INFO - [VLLM_CLIENT] Initializing PyNcclCommunicator on device 0, rank 2, world_size 3
INFO 06-07 17:34:25 [utils.py:1055] Found nccl from library libnccl.so.2
INFO 06-07 17:34:25 [pynccl.py:69] vLLM is using nccl==2.21.5

25ef2a5020cf:14816:14816 [0] init.cc:943 NCCL WARN Duplicate GPU detected : rank 2 and rank 0 both on CUDA device 25000
─────────────────────────────── ❌ Stage Failed ────────────────────────────────
❌ Stage identity failed: NCCL error: invalid usage (run with NCCL_DEBUG=WARN 
for details)
🛑 Stopping training
────────────────────────────────────────────────────────────────────────────────
[17:34:26] ERROR    Training failed: NCCL error: invalid usage (run with        
                    NCCL_DEBUG=WARN for details)                                
Traceback (most recent call last):
  File "/thauten/train_compressor.py", line 846, in <module>
    main()
  File "/thauten/train_compressor.py", line 820, in main
    current_model_path = train_stage(stage, compressor_env, current_model_path, base_model_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/thauten/train_compressor.py", line 711, in train_stage
    trainer = vf.GRPOTrainer(
              ^^^^^^^^^^^^^^^
  File "/venv/main/lib/python3.12/site-packages/verifiers/trainers/grpo_trainer.py", line 297, in __init__
    self.vllm_client.init_communicator()
  File "/venv/main/lib/python3.12/site-packages/verifiers/inference/vllm_client.py", line 177, in init_communicator
    self.pynccl_comm = PyNcclCommunicator(pg, device=device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/main/lib/python3.12/site-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
    self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/main/lib/python3.12/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
    self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
  File "/venv/main/lib/python3.12/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
    raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
```

Is verifiers incompatible with nccl 2.21.5 ?

The training code is over here if necessary https://github.com/holo-q/thauten/blob/master/train_compressor.py

**Comment by willccbb** [comment]
I'm only seeing it on H200 GPUs (CUDA 12.4). Reverting to older (or newer) versions of likely dependency culprits doesn't fix. 6000 Ada + H100 works fine for me.

**Comment by ayudhsaxena** [comment]
@willccbb Oh okay I see. Just to update, I've been facing some weird issues. Tried running one of the examples i.e math_python.py and it worked fine. Then i tried changing the same example with minimal changes  to incorporate my custom environment and it stopped working. Went back to running math_python.py to just verify once again and turns out that it stopped working as well ...

**Comment by ayudhsaxena** [comment]
@willccbb Okay seems like the issue for me was NCCL_P2P_DISABLE=1. I had this set since the older commits were giving a problem. Removing it worked for me! Although I dont completely understand why is that the case. 

Also idk if its bug or not, but seems like whenever training script exits with an error, then I have to relaunch the vllm server to avoid getting the same NCCL error.

**Comment by willccbb** [comment]
Funny enough, adding back in  `NCCL_P2P_DISABLE=1` fixed it for me. I'll update the readme docs to recommend toggling this on NCCL bugs. Seems to be a common workaround for driver issues, which are highly dependent on your machine's setup and are somewhat beyond scope of repo-level features. 

Yeah, relaunching the server is generally recommended if the crash occurs during the communication channel initialization (which will be the case for these NCCL errors).

More info: https://docs.vllm.ai/en/v0.6.6/getting_started/debugging.html#incorrect-hardware-driver

**Comment by ayudhsaxena** [comment]
@willccbb I've noticed it happens even if the crash occurs outside the communication channel initialization. Its not always though, possibly only when the vllm is generating or communicating, will have to confirm this. Is it just me or are you facing this as well?

**Comment by willccbb** [comment]
related to the health check ping maybe? is it still blocking if you have the flag set appropriately?

**Comment by oxysoft** [comment]
Unfortunately neither NCCL_P2P_DISABLE=1 or NCCL_P2P_DISABLE=0 succeeds to fix it for me, tried on both client and server, CUDA 12.6 on 2xA40

**Comment by oxysoft** [comment]
Okay I'll have to try again later this week but I think it went away last night after I pinned the version for vllm and flash attention to older releases so that I could use torch 2.6 which is what the cloud compute instance comes bundled with.

**Comment by ayudhsaxena** [comment]
@willccbb Hi Will, I am having the same NCCL errors while running verifiers on 8xL40S + torch 2.6 + CUDA 12.4 + NCCL 2.21.5. With `NCCL_P2P_DISABLE=0`, the code hangs while with `NCCL_P2P_DISABLE=1` it throws the NCCL error. On 6000Ada it works fine as we had discussed, but I want to be able to run on these other GPU configs as well, otherwise it becomes a serious bottleneck for me. If possible, could you share some pointers on how I could possibly go on to resolve this? Thanks a lot!

**Comment by willccbb** [comment]
what vLLM version are you using?

anything interesting if you run with NCCL_DEBUG=INFO?

this is usually an issue with your machine's driver setup, not something directly related to the library 

more info: https://docs.vllm.ai/en/v0.7.2/getting_started/troubleshooting.html

**Comment by hank0316** [comment]
Hi, I’m encountering the same NCCL error as others when running vLLM (0.9.1) and my training script on Saturn Cloud with 4xA100-80GB.
* CUDA: 12.6
* NCCL: 2.26.2
* PyTorch: 2.7.0+cu126
* vLLM: 0.9.1
* Platform: Saturn Cloud
* No custom changes to vLLM or trainer logic, but I slightly modified the deepspeed config.

The error seems to occur when initializing the client.

How I launch vLLM:
```bash
NCCL_DEBUG=INFO CUDA_VISIBLE_DEVICES=0,1 vf-vllm \
    --model 'Qwen/Qwen2.5-3B-Instruct' \
    --tensor-parallel-size 2 \
    --max-model-len 5120 \
    --dtype bfloat16 \
    --gpu-memory-utilization 0.9 \
    --enable-prefix-caching \
    --host 0.0.0.0 --port 8000
```

How I launch the training script:
```bash
CUDA_VISIBLE_DEVICES=2,3 accelerate launch \
    --config-file configs/zero3.yaml \
    --num-processes 2 verifiers/examples/exp/qa_train.py
```

Full vLLM log:
```
INFO 06-19 16:58:23 [__init__.py:244] Automatically detected platform cuda.
2025-06-19 16:58:25 - verifiers.inference.vllm_server - INFO - Starting Uvicorn with 1 worker(s). Data parallel size: 1
INFO:     Started server process [53771]
INFO:     Waiting for application startup.
2025-06-19 16:58:25 - verifiers.inference.vllm_server - INFO - Lifespan: Waiting for 1 LLM worker(s) to be ready...
INFO 06-19 16:58:32 [config.py:823] This model supports multiple tasks: {'reward', 'embed', 'score', 'generate', 'classify'}. Defaulting to 'generate'.
INFO 06-19 16:58:32 [config.py:2195] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 06-19 16:58:39 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 06-19 16:58:39 [__init__.py:244] Automatically detected platform cuda.
INFO 06-19 16:58:42 [core.py:455] Waiting for init message from front-end.
INFO 06-19 16:58:42 [core.py:70] Initializing a V1 LLM engine (v0.9.1) with config: model='Qwen/Qwen2.5-3B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-3B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=5120, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-3B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 06-19 16:58:42 [worker_base.py:590] Injected <class 'verifiers.inference.vllm_server.WeightSyncWorkerExtension'> into <class 'vllm.v1.worker.gpu_worker.Worker'> for extended collective_rpc calls ['close_communicator', 'init_communicator', 'update_named_param']
WARNING 06-19 16:58:42 [utils.py:2737] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7efb99557210>
INFO 06-19 16:58:43 [parallel_state.py:1065] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 06-19 16:58:43 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 06-19 16:58:43 [gpu_model_runner.py:1595] Starting to load model Qwen/Qwen2.5-3B-Instruct...
INFO 06-19 16:58:43 [gpu_model_runner.py:1600] Loading model from scratch...
INFO 06-19 16:58:43 [cuda.py:252] Using Flash Attention backend on V1 engine.
INFO 06-19 16:58:43 [weight_utils.py:292] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  3.54it/s]

Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.24it/s]

Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:00<00:00,  2.37it/s]

INFO 06-19 16:58:44 [default_loader.py:272] Loading weights took 0.96 seconds
INFO 06-19 16:58:45 [gpu_model_runner.py:1624] Model loading took 5.7923 GiB and 1.267424 seconds
INFO 06-19 16:58:52 [backends.py:462] Using cache directory: /home/jovyan/.cache/vllm/torch_compile_cache/b55835aa3d/rank_0_0 for vLLM's torch.compile
INFO 06-19 16:58:52 [backends.py:472] Dynamo bytecode transform time: 7.18 s
INFO 06-19 16:58:58 [backends.py:135] Directly load the compiled graph(s) for shape None from the cache, took 5.846 s
INFO 06-19 16:58:59 [monitor.py:34] torch.compile takes 7.18 s in total
INFO 06-19 16:59:00 [gpu_worker.py:227] Available KV cache memory: 59.92 GiB
INFO 06-19 16:59:01 [kv_cache_utils.py:715] GPU KV cache size: 1,745,264 tokens
INFO 06-19 16:59:01 [kv_cache_utils.py:719] Maximum concurrency for 5,120 tokens per request: 340.87x
INFO 06-19 16:59:22 [gpu_model_runner.py:2048] Graph capturing finished in 21 secs, took 0.55 GiB
INFO 06-19 16:59:22 [core.py:171] init engine (profile, create kv cache, warmup model) took 37.37 seconds
2025-06-19 16:59:23 - verifiers.inference.vllm_server - INFO - Lifespan: Received message from worker 0: {'status': 'ready'}
2025-06-19 16:59:23 - verifiers.inference.vllm_server - INFO - Lifespan: LLM worker 0 reported ready.
2025-06-19 16:59:23 - verifiers.inference.vllm_server - INFO - Lifespan: All 1 LLM worker(s) are ready. Proceeding to yield.
2025-06-19 16:59:23 - verifiers.inference.vllm_server - INFO - Lifespan: Initialized request queue for batched chat completions.
2025-06-19 16:59:23 - verifiers.inference.vllm_server - INFO - Lifespan: Started batch processing task for chat completions.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:33496 - "GET /health/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:33500 - "GET /get_world_size/ HTTP/1.1" 200 OK
2025-06-19 16:59:50 - verifiers.inference.vllm_server - INFO - [INIT_COMMUNICATOR] Received request: host=0.0.0.0, port=51216, world_size=2
2025-06-19 16:59:50 - verifiers.inference.vllm_server - INFO - [INIT_COMMUNICATOR] vLLM world size: 1 (TP=1 x DP=1)
2025-06-19 16:59:50 - verifiers.inference.vllm_server - INFO - [INIT_COMMUNICATOR] Expected total world size: 2
2025-06-19 16:59:50 - verifiers.inference.vllm_server - INFO - [INIT_COMMUNICATOR] Successfully notified 1 workers
INFO:     127.0.0.1:33512 - "POST /init_communicator/ HTTP/1.1" 200 OK
2025-06-19 16:59:50 - verifiers.inference.vllm_server - INFO - [WORKER] Initializing communicator: rank=0, device=cuda:0, world_size=2
INFO 06-19 16:59:50 [utils.py:1126] Found nccl from library libnccl.so.2
INFO 06-19 16:59:50 [pynccl.py:70] vLLM is using nccl==2.26.2
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Bootstrap: Using eth0:192.168.156.86<0>
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO cudaDriverVersion 12060
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO NCCL version 2.26.2+cuda12.2
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO NET/Plugin: Could not find: libnccl-net.so. Using internal net plugin.
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Failed to open libibverbs.so[.1]
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.156.86<0>
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO PROFILER/Plugin: Could not find: libnccl-profiler.so. 
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Using network Socket
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO ncclCommInitRank comm 0x56113290eca0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId f000 commId 0x94895eff3c5c5abd - Init START
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO RAS client listening socket at ::1<28028>
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Bootstrap timings total 0.000675 (create 0.000031, send 0.000097, recv 0.000172, ring 0.000025, delay 0.000000)
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Setting affinity for GPU 0 to ffff0000,00000000,00000000,00000000,ffff0000,00000000
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO comm 0x56113290eca0 rank 0 nRanks 2 nNodes 1 localRanks 2 localRank 0 MNNVL 0
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 00/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 01/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 02/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 03/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 04/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 05/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 06/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 07/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 08/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 09/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 10/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 11/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 12/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 13/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 14/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 15/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 16/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 17/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 18/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 19/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 20/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 21/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 22/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 23/24 : 0 1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1 [4] 1/-1/-1->0->-1 [5] 1/-1/-1->0->-1 [6] -1/-1/-1->0->1 [7] -1/-1/-1->0->1 [8] -1/-1/-1->0->1 [9] -1/-1/-1->0->1 [10] -1/-1/-1->0->1 [11] -1/-1/-1->0->1 [12] 1/-1/-1->0->-1 [13] 1/-1/-1->0->-1 [14] 1/-1/-1->0->-1 [15] 1/-1/-1->0->-1 [16] 1/-1/-1->0->-1 [17] 1/-1/-1->0->-1 [18] -1/-1/-1->0->1 [19] -1/-1/-1->0->1 [20] -1/-1/-1->0->1 [21] -1/-1/-1->0->1 [22] -1/-1/-1->0->1 [23] -1/-1/-1->0->1
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO P2P Chunksize set to 524288
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Check P2P Type intraNodeP2pSupport 1 directMode 0
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:55485 [0] NCCL INFO [Proxy Service UDS] Device 0 CPU core 177
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:55484 [0] NCCL INFO [Proxy Service] Device 0 CPU core 59
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 02/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 03/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 04/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 05/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 06/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 07/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 08/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 09/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 10/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 11/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 12/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 13/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 14/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 15/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 16/0 : 0[0] -> 1[1] via P2P/IPC/read
w-hank0-run-rl-51ae17c445464136b08939a0d411cb2d-df99c54dd-xktdk:54079:54079 [0] NCCL INFO Channel 17/0 : 0[0] -> 1ERROR 06-19 16:59:50 [core.py:583] Invocation of collective_rpc method failed
ERROR 06-19 16:59:50 [core.py:583] Traceback (most recent call last):
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 580, in _handle_client_request
ERROR 06-19 16:59:50 [core.py:583]     output.result = method(
ERROR 06-19 16:59:50 [core.py:583]                     ^^^^^^^
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 347, in collective_rpc
ERROR 06-19 16:59:50 [core.py:583]     return self.model_executor.collective_rpc(method, timeout, args,
ERROR 06-19 16:59:50 [core.py:583]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
ERROR 06-19 16:59:50 [core.py:583]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 06-19 16:59:50 [core.py:583]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/utils.py", line 2671, in run_method
ERROR 06-19 16:59:50 [core.py:583]     return func(*args, **kwargs)
ERROR 06-19 16:59:50 [core.py:583]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/verifiers/inference/vllm_server.py", line 223, in init_communicator
ERROR 06-19 16:59:50 [core.py:583]     self.pynccl_comm = PyNcclCommunicator(pg, device=self.device) # type: ignore
ERROR 06-19 16:59:50 [core.py:583]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl.py", line 100, in __init__
ERROR 06-19 16:59:50 [core.py:583]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
ERROR 06-19 16:59:50 [core.py:583]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 278, in ncclCommInitRank
ERROR 06-19 16:59:50 [core.py:583]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
ERROR 06-19 16:59:50 [core.py:583]   File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 257, in NCCL_CHECK
ERROR 06-19 16:59:50 [core.py:583]     raise RuntimeError(f"NCCL error: {error_str}")
ERROR 06-19 16:59:50 [core.py:583] RuntimeError: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
2025-06-19 16:59:50 - verifiers.inference.vllm_server - ERROR - [WORKER 0] Error in collective_rpc: Call to collective_rpc method failed: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
Traceback (most recent call last):
  File "/home/jovyan/workspace/MRT-verifiers/verifiers/inference/vllm_server.py", line 575, in llm_worker
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 505, in collective_rpc
    return self.llm_engine.collective_rpc(method, timeout, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 313, in collective_rpc
    return self.engine_core.collective_rpc(method, timeout, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 697, in collective_rpc
    return self.call_utility("collective_rpc", method, timeout, args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/MRT-verifiers/.venv/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 650, in call_utility
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/saturncloud/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/saturncloud/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
Exception: Call to collective_rpc method failed: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
```

Deepspeed Config (yaml):
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: configs/zero3.json
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
# mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

`configs/zero3.json`:
```json
{
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "zero_allow_untested_optimizer": true,
    "fp16": {
      "enabled": "auto",
      "loss_scale": 0,
      "loss_scale_window": 1000,
      "initial_scale_power": 16,
      "hysteresis": 2,
      "min_loss_scale": 1
    },
    "bf16": {
      "enabled": "auto"
    },
    "zero_optimization": {
      "stage": 3,
      "overlap_comm": false,
      "contiguous_gradients": true,
      "sub_group_size": 1e9,
      "reduce_bucket_size": "auto",
      "stage3_prefetch_bucket_size": "auto",
      "stage3_param_persistence_threshold": "auto",
      "stage3_max_live_parameters": 1e9,
      "stage3_max_reuse_distance": 1e9,
      "stage3_gather_16bit_weights_on_model_save": true
    }
  }
```

And actually I have run the `test.py` from vLLM  [here](https://docs.vllm.ai/en/v0.7.2/getting_started/troubleshooting.html#incorrect-hardware-driver). And I got assertion error at `line 43` before `print("vLLM NCCL is successful!")`. Does it means that the driver on the compute platform has some issue?

**Comment by hank0316** [comment]
@sachit-menon What GPU driver, CUDA, and NCCL versions are you using?
